[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"   # or 20 depending on your package-lock / engine